### ISSUE TITLE
Facing same issue after fresh setup of Aadhaar gateway.

### ISSUE THREAD

**Issue by tdesai79** [khosla-labs/aadhaar-bridge#17]
Hello Sahil,
While things were working smooth with our server, due to some server crash, we had to setup the environment again. This time, we have followed same steps again to setup aadhaar gateway. However, we are getting same issue which you had resolved last time where the Aadhar check was always returning False result even though the data is correct. Server details are same as before. Copying for your reference
Server is : http://103.247.149.33
Port is : 8181 
If you had done any changes last time to correct the server please mention the same.
Properties File : 
keystore.location=/cert/emmersive.p12
keystore.pass=RatRaRa2
keystore.alias=emmersivepoc
x09cert.location=/cert/DKbf33ec.cer
aua.host.auth.url=https://bridgetest.aadhaarconnect.com/aua/auth
aua.host.bfd.url=https://bridgetest.aadhaarconnect.com/aua/bfd
aua.host.otp.url=https://bridgetest.aadhaarconnect.com/aua/otp
aua.host.kyc.url=https://bridgetest.aadhaarconnect.com/aua/kyc
subaua.code=DKbf33ec
timeout.in.sec=300000

server.port=8181

**Comment by guneshpatil** [comment]
Even I am facing issues with Gateway server setup. I had contacted your tech support but not able to get a solution on this. I have followed all steps as mentioned on the portal and on github readME. Please find the stack trace as below:
```
[nio-8583-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: java.io.IOException: failed to decrypt safe contents entry: javax.crypto.BadPaddingException: Given final block not properly padded] with root cause

javax.crypto.BadPaddingException: Given final block not properly padded
        at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:811)
        at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:676)
        at com.sun.crypto.provider.PKCS12PBECipherCore.implDoFinal(PKCS12PBECipherCore.java:355)
        at com.sun.crypto.provider.PKCS12PBECipherCore$PBEWithSHA1AndRC2_40.engineDoFinal(PKCS12PBECipherCore.java:462)
        at javax.crypto.Cipher.doFinal(Cipher.java:1966)
        at sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:1308)
        at java.security.KeyStore.load(KeyStore.java:1226)
        at com.aadhaarconnect.bridge.security.XMLSigner.getPrivateKeyEntry(XMLSigner.java:155)
        at com.aadhaarconnect.bridge.security.XMLSigner.signXML(XMLSigner.java:100)
        at com.aadhaarconnect.bridge.aua.delegates.AbstractDelegate.sign(AbstractDelegate.java:158)
        at com.aadhaarconnect.bridge.aua.delegates.AuthDelegate.signXml(AuthDelegate.java:55)
        at com.aadhaarconnect.bridge.aua.spi.support.AadhaarConnectAuth.sign(AadhaarConnectAuth.java:46)
        at com.aadhaarconnect.bridge.gate.AadhaarGatewayController.auth(AadhaarGatewayController.java:126)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:749)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:689)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:83)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:938)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:870)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:961)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:863)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:837)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1736)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1695)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by Dipkatts** [comment]
We are all getting the errors. And no solution yet -_-

**Comment by Dipkatts** [comment]
We are also having same  problem

**Comment by jaydeep1993** [comment]
We will not be answering any query/issue on github. Please mail us your issue and we will raise a ticket on our HelpDesk. Please use below mentioned email-ids for the same.

For any business related query, Drop an email at [customer.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

For Technical query, Drop email at [tech.support@aadhaarbridge.com](tech.support@aadhaarbridge.com)

Contact info can be found [here](http://aadhaarbridge.com/contact.html).
