### ISSUE TITLE
java.io.FileNotFoundException while accessing x09cert.location application.properties value in XMLSigner.class

### ISSUE THREAD

**Issue by chainsingh** [khosla-labs/aadhaar-bridge#18]
On running kua-gateway-server as java -jar aadhaarbridge-kua-gate-0.0.1-SNAPSHOT.jar and application.properties as:
"keystore.location=/Users/chainsingh/Downloads/server/ETa8cd3f.p12
keystore.pass=****
keystore.alias=aadharbridgeKey
x09cert.location=/Users/chainsingh/Downloads/server/ETa8cd3f.cer 
aua.host.auth.url=http://localhost:8085/kua-preprod/auth
aua.host.bfd.url=http://localhost:8085/kua-preprod/bfd
aua.host.otp.url=http://localhost:8085/kua-preprod/otp
aua.host.kyc.url=http://localhost:8085/kua-preprod/kyc
subaua.code=ETa8cd3f
timeout.in.sec=300000
server.port=8181", 
and hitting http://localhost:8181/auth/raw with request json as 
{
        "aadhaar-id": "645446389945",
        "location": {
            "type": "pincode",
            "pincode": "560067"
        },
        "modality": "demo",
        "certificate-type": "prod",
        "demographics": {
            "name": {
                "matching-strategy": "exact",
                "name-value": "Sahil Mutneja"
            }
        }
} 
is consistently resulting in following error:
java.lang.RuntimeException: java.io.FileNotFoundException:
/Users/chainsingh/Downloads/server/ETa8cd3f.cer  (No such file or directory)
        at com.aadhaarconnect.bridge.security.XMLSigner.getPublicKey(XMLSigner.java:190)
        at com.aadhaarconnect.bridge.security.XMLSigner.signXML(XMLSigner.java:100)

**even when this actually exists.**  Putting the 

Running the same snippet of code of accessing file in XMLSigner.getPublicKey in a standalone java program does not result in any error. When I put /Users/chainsingh/Downloads/server/ETa8cd3f.cer in keystore.location it is able to find the file. I am, to be frank, left with no explanation for this behaviour excpet there may be some non-trivial issue in the code itself.

**Comment by chainsingh** [comment]
Sorry my mistake. Was a silly error.
